name: List runner applications for an organization
description: |-
  Lists binaries for the runner application that you can download and run.

  Authenticated users must have admin access to the organization to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.  If the repository is private, the `repo` scope is also required.
env: null
vars: null
setup: null
tests:
- name: List runner applications for an organization
  description: |-
    Lists binaries for the runner application that you can download and run.

    Authenticated users must have admin access to the organization to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.  If the repository is private, the `repo` scope is also required.
  request:
    method: GET
    url: https://api.github.com/orgs/{org}/actions/runners/downloads
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
