name: Delete an environment variable
description: |-
  Deletes an environment variable using the variable name.

  Authenticated users must have collaborator access to a repository to create, update, or read variables.

  OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Delete an environment variable
  description: |-
    Deletes an environment variable using the variable name.

    Authenticated users must have collaborator access to a repository to create, update, or read variables.

    OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: DELETE
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}/variables/{name}
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
