name: Set private repo fork PR workflow settings for a repository
description: |-
  Sets the settings for whether workflows from fork pull requests can run on a private repository.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Set private repo fork PR workflow settings for a repository
  description: |-
    Sets the settings for whether workflows from fork pull requests can run on a private repository.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: PUT
    url: https://api.github.com/repos/{owner}/{repo}/actions/permissions/fork-pr-workflows-private-repos
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
