name: Set artifact and log retention settings for a repository
description: |-
  Sets artifact and log retention settings for a repository.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Set artifact and log retention settings for a repository
  description: |-
    Sets artifact and log retention settings for a repository.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: PUT
    url: https://api.github.com/repos/{owner}/{repo}/actions/permissions/artifact-and-log-retention
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
