name: Create configuration for a just-in-time runner for an organization
description: |-
  Generates a configuration that can be passed to the runner application at startup.

  The authenticated user must have admin access to the organization.

  OAuth tokens and personal access tokens (classic) need the`admin:org` scope to use this endpoint. If the repository is private, OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create configuration for a just-in-time runner for an organization
  description: |-
    Generates a configuration that can be passed to the runner application at startup.

    The authenticated user must have admin access to the organization.

    OAuth tokens and personal access tokens (classic) need the`admin:org` scope to use this endpoint. If the repository is private, OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/orgs/{org}/actions/runners/generate-jitconfig
    headers: null
    params: null
    body: |-
      {
        "labels": [
          "example"
        ],
        "name": "example",
        "runner_group_id": 42,
        "work_folder": "example"
      }
  expect:
    status: 201
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
