name: Get private repo fork PR workflow settings for an organization
description: Gets the settings for whether workflows from fork pull requests can run on private repositories in an organization.
env: null
vars: null
setup: null
tests:
- name: Get private repo fork PR workflow settings for an organization
  description: Gets the settings for whether workflows from fork pull requests can run on private repositories in an organization.
  request:
    method: GET
    url: https://api.github.com/orgs/{org}/actions/permissions/fork-pr-workflows-private-repos
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
