name: Set artifact and log retention settings for an organization
description: |-
  Sets artifact and log retention settings for an organization.

  OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Set artifact and log retention settings for an organization
  description: |-
    Sets artifact and log retention settings for an organization.

    OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
  request:
    method: PUT
    url: https://api.github.com/orgs/{org}/actions/permissions/artifact-and-log-retention
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
