name: List runner applications for a repository
description: |-
  Lists binaries for the runner application that you can download and run.

  Authenticated users must have admin access to the repository to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: List runner applications for a repository
  description: |-
    Lists binaries for the runner application that you can download and run.

    Authenticated users must have admin access to the repository to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/actions/runners/downloads
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
