name: Get an environment secret
description: |-
  Gets a single environment secret without revealing its encrypted value.

  Authenticated users must have collaborator access to a repository to create, update, or read secrets.

  OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get an environment secret
  description: |-
    Gets a single environment secret without revealing its encrypted value.

    Authenticated users must have collaborator access to a repository to create, update, or read secrets.

    OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}/secrets/{secret_name}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
