name: Create a code security configuration for an enterprise
description: |-
  Creates a code security configuration in an enterprise.

  The authenticated user must be an administrator of the enterprise in order to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create a code security configuration for an enterprise
  description: |-
    Creates a code security configuration in an enterprise.

    The authenticated user must be an administrator of the enterprise in order to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations
    headers: null
    params: null
    body: |-
      {
        "advanced_security": "example",
        "code_scanning_default_setup": "example",
        "code_scanning_delegated_alert_dismissal": "example",
        "code_security": "example",
        "dependabot_alerts": "example",
        "dependabot_security_updates": "example",
        "dependency_graph": "example",
        "dependency_graph_autosubmit_action": "example",
        "dependency_graph_autosubmit_action_options": {},
        "description": "example",
        "enforcement": "example",
        "name": "example",
        "private_vulnerability_reporting": "example",
        "secret_protection": "example",
        "secret_scanning": "example",
        "secret_scanning_delegated_alert_dismissal": "example",
        "secret_scanning_generic_secrets": "example",
        "secret_scanning_non_provider_patterns": "example",
        "secret_scanning_push_protection": "example",
        "secret_scanning_validity_checks": "example"
      }
  expect:
    status: 201
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
