name: Get the code security configuration associated with a repository
description: |-
  Get the code security configuration that manages a repository's code security settings.

  The authenticated user must be an administrator or security manager for the organization to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get the code security configuration associated with a repository
  description: |-
    Get the code security configuration that manages a repository's code security settings.

    The authenticated user must be an administrator or security manager for the organization to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/code-security-configuration
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
