name: Retrieve a code security configuration of an enterprise
description: |-
  Gets a code security configuration available in an enterprise.

  The authenticated user must be an administrator of the enterprise in order to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `read:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Retrieve a code security configuration of an enterprise
  description: |-
    Gets a code security configuration available in an enterprise.

    The authenticated user must be an administrator of the enterprise in order to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `read:enterprise` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations/{configuration_id}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
