name: Set a code security configuration as a default for an enterprise
description: |-
  Sets a code security configuration as a default to be applied to new repositories in your enterprise.

  This configuration will be applied by default to the matching repository type when created, but only for organizations within the enterprise that do not already have a default code security configuration set.

  The authenticated user must be an administrator for the enterprise to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Set a code security configuration as a default for an enterprise
  description: |-
    Sets a code security configuration as a default to be applied to new repositories in your enterprise.

    This configuration will be applied by default to the matching repository type when created, but only for organizations within the enterprise that do not already have a default code security configuration set.

    The authenticated user must be an administrator for the enterprise to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
  request:
    method: PUT
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations/{configuration_id}/defaults
    headers: null
    params: null
    body: |-
      {
        "default_for_new_repos": "example"
      }
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
