name: Delete a code security configuration for an enterprise
description: |-
  Deletes a code security configuration from an enterprise.
  Repositories attached to the configuration will retain their settings but will no longer be associated with
  the configuration.

  The authenticated user must be an administrator for the enterprise to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Delete a code security configuration for an enterprise
  description: |-
    Deletes a code security configuration from an enterprise.
    Repositories attached to the configuration will retain their settings but will no longer be associated with
    the configuration.

    The authenticated user must be an administrator for the enterprise to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
  request:
    method: DELETE
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations/{configuration_id}
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
