name: Attach an enterprise configuration to repositories
description: |-
  Attaches an enterprise code security configuration to repositories. If the repositories specified are already attached to a configuration, they will be re-attached to the provided configuration.

  If insufficient GHAS licenses are available to attach the configuration to a repository, only free features will be enabled.

  The authenticated user must be an administrator for the enterprise to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Attach an enterprise configuration to repositories
  description: |-
    Attaches an enterprise code security configuration to repositories. If the repositories specified are already attached to a configuration, they will be re-attached to the provided configuration.

    If insufficient GHAS licenses are available to attach the configuration to a repository, only free features will be enabled.

    The authenticated user must be an administrator for the enterprise to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations/{configuration_id}/attach
    headers: null
    params: null
    body: |-
      {
        "scope": "example"
      }
  expect:
    status: 202
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
