name: Get repositories associated with an enterprise code security configuration
description: |-
  Lists the repositories associated with an enterprise code security configuration in an organization.

  The authenticated user must be an administrator of the enterprise in order to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `read:enterprise` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get repositories associated with an enterprise code security configuration
  description: |-
    Lists the repositories associated with an enterprise code security configuration in an organization.

    The authenticated user must be an administrator of the enterprise in order to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `read:enterprise` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/enterprises/{enterprise}/code-security/configurations/{configuration_id}/repositories
    headers: null
    params:
      per_page: '{{queryValue}}'
      status: '{{queryValue}}'
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
