name: Detach configurations from repositories
description: |-
  Detach code security configuration(s) from a set of repositories.
  Repositories will retain their settings but will no longer be associated with the configuration.

  The authenticated user must be an administrator or security manager for the organization to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Detach configurations from repositories
  description: |-
    Detach code security configuration(s) from a set of repositories.
    Repositories will retain their settings but will no longer be associated with the configuration.

    The authenticated user must be an administrator or security manager for the organization to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
  request:
    method: DELETE
    url: https://api.github.com/orgs/{org}/code-security/configurations/detach
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
