name: Get a code security configuration
description: |-
  Gets a code security configuration available in an organization.

  The authenticated user must be an administrator or security manager for the organization to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get a code security configuration
  description: |-
    Gets a code security configuration available in an organization.

    The authenticated user must be an administrator or security manager for the organization to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/orgs/{org}/code-security/configurations/{configuration_id}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
