name: Attach a configuration to repositories
description: |-
  Attach a code security configuration to a set of repositories. If the repositories specified are already attached to a configuration, they will be re-attached to the provided configuration.

  If insufficient GHAS licenses are available to attach the configuration to a repository, only free features will be enabled.

  The authenticated user must be an administrator or security manager for the organization to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Attach a configuration to repositories
  description: |-
    Attach a code security configuration to a set of repositories. If the repositories specified are already attached to a configuration, they will be re-attached to the provided configuration.

    If insufficient GHAS licenses are available to attach the configuration to a repository, only free features will be enabled.

    The authenticated user must be an administrator or security manager for the organization to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/orgs/{org}/code-security/configurations/{configuration_id}/attach
    headers: null
    params: null
    body: |-
      {
        "scope": "example",
        "selected_repository_ids": [
          "example"
        ]
      }
  expect:
    status: 202
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
