name: List Dependabot alerts for an enterprise
description: |-
  Lists Dependabot alerts for repositories that are owned by the specified enterprise.

  The authenticated user must be a member of the enterprise to use this endpoint.

  Alerts are only returned for organizations in the enterprise for which you are an organization owner or a security manager. For more information about security managers, see "[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)."

  OAuth app tokens and personal access tokens (classic) need the `repo` or `security_events` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: List Dependabot alerts for an enterprise
  description: |-
    Lists Dependabot alerts for repositories that are owned by the specified enterprise.

    The authenticated user must be a member of the enterprise to use this endpoint.

    Alerts are only returned for organizations in the enterprise for which you are an organization owner or a security manager. For more information about security managers, see "[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)."

    OAuth app tokens and personal access tokens (classic) need the `repo` or `security_events` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/enterprises/{enterprise}/dependabot/alerts
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
