name: Remove selected repository from an organization secret
description: |-
  Removes a repository from an organization secret when the `visibility`
  for repository access is set to `selected`. The visibility is set when you [Create
  or update an organization secret](https://docs.github.com/rest/dependabot/secrets#create-or-update-an-organization-secret).

  OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Remove selected repository from an organization secret
  description: |-
    Removes a repository from an organization secret when the `visibility`
    for repository access is set to `selected`. The visibility is set when you [Create
    or update an organization secret](https://docs.github.com/rest/dependabot/secrets#create-or-update-an-organization-secret).

    OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
  request:
    method: DELETE
    url: https://api.github.com/orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
