name: Lists the repositories Dependabot can access in an organization
description: |-
  Lists repositories that organization admins have allowed Dependabot to access when updating dependencies.
  > [!NOTE]
  >    This operation supports both server-to-server and user-to-server access.
  Unauthorized users will not see the existence of this endpoint.
env: null
vars: null
setup: null
tests:
- name: Lists the repositories Dependabot can access in an organization
  description: |-
    Lists repositories that organization admins have allowed Dependabot to access when updating dependencies.
    > [!NOTE]
    >    This operation supports both server-to-server and user-to-server access.
    Unauthorized users will not see the existence of this endpoint.
  request:
    method: GET
    url: https://api.github.com/organizations/{org}/dependabot/repository-access
    headers: null
    params:
      per_page: '{{queryValue}}'
      page: '{{queryValue}}'
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
