name: List repository secrets
description: |-
  Lists all secrets available in a repository without revealing their encrypted
  values.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: List repository secrets
  description: |-
    Lists all secrets available in a repository without revealing their encrypted
    values.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/dependabot/secrets
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
