name: Get a repository secret
description: |-
  Gets a single repository secret without revealing its encrypted value.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get a repository secret
  description: |-
    Gets a single repository secret without revealing its encrypted value.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
