name: List Dependabot alerts for a repository
description: OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint. If this endpoint is only used with public repositories, the token can use the `public_repo` scope instead.
env: null
vars: null
setup: null
tests:
- name: List Dependabot alerts for a repository
  description: OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint. If this endpoint is only used with public repositories, the token can use the `public_repo` scope instead.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/dependabot/alerts
    headers: null
    params:
      per_page: '{{queryValue}}'
      page: '{{queryValue}}'
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
