name: Updates Dependabot's repository access list for an organization
description: |-
  Updates repositories according to the list of repositories that organization admins have given Dependabot access to when they've updated dependencies.

  > [!NOTE]
  >    This operation supports both server-to-server and user-to-server access.
  Unauthorized users will not see the existence of this endpoint.

  **Example request body:**
  ```json
  {
    "repository_ids_to_add": [123, 456],
    "repository_ids_to_remove": [789]
  }
  ```
env: null
vars: null
setup: null
tests:
- name: Updates Dependabot's repository access list for an organization
  description: |-
    Updates repositories according to the list of repositories that organization admins have given Dependabot access to when they've updated dependencies.

    > [!NOTE]
    >    This operation supports both server-to-server and user-to-server access.
    Unauthorized users will not see the existence of this endpoint.

    **Example request body:**
    ```json
    {
      "repository_ids_to_add": [123, 456],
      "repository_ids_to_remove": [789]
    }
    ```
  request:
    method: PATCH
    url: https://api.github.com/organizations/{org}/dependabot/repository-access
    headers: null
    params: null
    body: |-
      {
        "repository_ids_to_add": [
          "example"
        ],
        "repository_ids_to_remove": [
          "example"
        ]
      }
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
