name: Get a hosted compute network settings resource for an organization
description: |-
  Gets a hosted compute network settings resource configured for an organization.

  OAuth app tokens and personal access tokens (classic) need the `read:network_configurations` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Get a hosted compute network settings resource for an organization
  description: |-
    Gets a hosted compute network settings resource configured for an organization.

    OAuth app tokens and personal access tokens (classic) need the `read:network_configurations` scope to use this endpoint.
  request:
    method: GET
    url: https://api.github.com/orgs/{org}/settings/network-settings/{network_settings_id}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
