name: Create a hosted compute network configuration for an organization
description: |-
  Creates a hosted compute network configuration for an organization.

  OAuth app tokens and personal access tokens (classic) need the `write:network_configurations` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create a hosted compute network configuration for an organization
  description: |-
    Creates a hosted compute network configuration for an organization.

    OAuth app tokens and personal access tokens (classic) need the `write:network_configurations` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/orgs/{org}/settings/network-configurations
    headers: null
    params: null
    body: |-
      {
        "compute_service": "example",
        "name": "example",
        "network_settings_ids": [
          "example"
        ]
      }
  expect:
    status: 201
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
