name: Update a webhook configuration for an organization
description: |-
  Updates the webhook configuration for an organization. To update more information about the webhook, including the `active` state and `events`, use "[Update an organization webhook ](/rest/orgs/webhooks#update-an-organization-webhook)."

  You must be an organization owner to use this endpoint.

  OAuth app tokens and personal access tokens (classic) need `admin:org_hook` scope. OAuth apps cannot list, view, or edit
  webhooks that they did not create and users cannot list, view, or edit webhooks that were created by OAuth apps.
env: null
vars: null
setup: null
tests:
- name: Update a webhook configuration for an organization
  description: |-
    Updates the webhook configuration for an organization. To update more information about the webhook, including the `active` state and `events`, use "[Update an organization webhook ](/rest/orgs/webhooks#update-an-organization-webhook)."

    You must be an organization owner to use this endpoint.

    OAuth app tokens and personal access tokens (classic) need `admin:org_hook` scope. OAuth apps cannot list, view, or edit
    webhooks that they did not create and users cannot list, view, or edit webhooks that were created by OAuth apps.
  request:
    method: PATCH
    url: https://api.github.com/orgs/{org}/hooks/{hook_id}/config
    headers: null
    params: null
    body: '{}'
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
