name: Create a deployment branch policy
description: |-
  Creates a deployment branch or tag policy for an environment.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create a deployment branch policy
  description: |-
    Creates a deployment branch or tag policy for an environment.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
