name: List deployment statuses
description: 'Users with pull access can view deployment statuses for a deployment:'
env: null
vars: null
setup: null
tests:
- name: List deployment statuses
  description: 'Users with pull access can view deployment statuses for a deployment:'
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/deployments/{deployment_id}/statuses
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
