name: Create or update an environment
description: |-
  Create or update an environment with protection rules, such as required reviewers. For more information about environment protection rules, see "[Environments](/actions/reference/environments#environment-protection-rules)."

  > [!NOTE]
  > To create or update name patterns that branches must match in order to deploy to this environment, see "[Deployment branch policies](/rest/deployments/branch-policies)."

  > [!NOTE]
  > To create or update secrets for an environment, see "[GitHub Actions secrets](/rest/actions/secrets)."

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create or update an environment
  description: |-
    Create or update an environment with protection rules, such as required reviewers. For more information about environment protection rules, see "[Environments](/actions/reference/environments#environment-protection-rules)."

    > [!NOTE]
    > To create or update name patterns that branches must match in order to deploy to this environment, see "[Deployment branch policies](/rest/deployments/branch-policies)."

    > [!NOTE]
    > To create or update secrets for an environment, see "[GitHub Actions secrets](/rest/actions/secrets)."

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: PUT
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}
    headers: null
    params: null
    body: |-
      {
        "reviewers": [
          "example"
        ]
      }
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
