name: Get an environment
description: |-
  > [!NOTE]
  > To get information about name patterns that branches must match in order to deploy to this environment, see "[Get a deployment branch policy](/rest/deployments/branch-policies#get-a-deployment-branch-policy)."

  Anyone with read access to the repository can use this endpoint.

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with a private repository.
env: null
vars: null
setup: null
tests:
- name: Get an environment
  description: |-
    > [!NOTE]
    > To get information about name patterns that branches must match in order to deploy to this environment, see "[Get a deployment branch policy](/rest/deployments/branch-policies#get-a-deployment-branch-policy)."

    Anyone with read access to the repository can use this endpoint.

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with a private repository.
  request:
    method: GET
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}
    headers: null
    params: null
    body: null
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
