name: Delete an environment
description: OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Delete an environment
  description: OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: DELETE
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}
    headers: null
    params: null
    body: null
  expect:
    status: 204
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
