name: Update a webhook configuration for a repository
description: |-
  Updates the webhook configuration for a repository. To update more information about the webhook, including the `active` state and `events`, use "[Update a repository webhook](/rest/webhooks/repos#update-a-repository-webhook)."

  OAuth app tokens and personal access tokens (classic) need the `write:repo_hook` or `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Update a webhook configuration for a repository
  description: |-
    Updates the webhook configuration for a repository. To update more information about the webhook, including the `active` state and `events`, use "[Update a repository webhook](/rest/webhooks/repos#update-a-repository-webhook)."

    OAuth app tokens and personal access tokens (classic) need the `write:repo_hook` or `repo` scope to use this endpoint.
  request:
    method: PATCH
    url: https://api.github.com/repos/{owner}/{repo}/hooks/{hook_id}/config
    headers: null
    params: null
    body: '{}'
  expect:
    status: 200
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
