name: Create a custom deployment protection rule on an environment
description: |-
  Enable a custom deployment protection rule for an environment.

  The authenticated user must have admin or owner permissions to the repository to use this endpoint.

  For more information about the app that is providing this custom deployment rule, see the [documentation for the `GET /apps/{app_slug}` endpoint](https://docs.github.com/rest/apps/apps#get-an-app), as well as the [guide to creating custom deployment protection rules](https://docs.github.com/actions/managing-workflow-runs-and-deployments/managing-deployments/creating-custom-deployment-protection-rules).

  OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
env: null
vars: null
setup: null
tests:
- name: Create a custom deployment protection rule on an environment
  description: |-
    Enable a custom deployment protection rule for an environment.

    The authenticated user must have admin or owner permissions to the repository to use this endpoint.

    For more information about the app that is providing this custom deployment rule, see the [documentation for the `GET /apps/{app_slug}` endpoint](https://docs.github.com/rest/apps/apps#get-an-app), as well as the [guide to creating custom deployment protection rules](https://docs.github.com/actions/managing-workflow-runs-and-deployments/managing-deployments/creating-custom-deployment-protection-rules).

    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
  request:
    method: POST
    url: https://api.github.com/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
    headers: null
    params: null
    body: |-
      {
        "integration_id": 42
      }
  expect:
    status: 201
    schema: null
    jsonpath: null
    headers: null
dataset: null
teardown: null
