name: build-deb

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-deb-amd64:
    name: Build .deb (amd64)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build (release)
        run: cargo build --release

      - name: Generate shell completions and man page
        run: |
          # Bash
          target/release/rivet completions bash > packaging/assets/completions/rivet.bash
          # Zsh
          target/release/rivet completions zsh > packaging/assets/completions/_rivet
          # Fish
          target/release/rivet completions fish > packaging/assets/completions/rivet.fish
          # Man page
          target/release/rivet man > packaging/assets/man/rivet.1

      - name: Build Debian package
        run: cargo deb --no-build

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: rivet-deb-amd64
          path: target/debian/*.deb
