name: Workflow Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [ main, develop ]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1

